### ISSUE TITLE
Admin panel crashes when signing in.

### ISSUE THREAD

**Issue by kuyugama** [vsdudakov/fastadmin#26]
Admin user identifier is always string.

```
Traceback (most recent call last):
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 515, in execute
    self._adapt_connection.await_(
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 494, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 444, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 717, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: '3' ('str' object cannot be interpreted as an integer)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\ratelimit\core.py", line 88, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
    raise app_exc
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 109, in __call__
    await response(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 134, in stream_response
    return await super().stream_response(send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 98, in body_stream
    raise app_exc
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastadmin\api\frameworks\fastapi\api.py", line 329, in configuration
    return await api_service.get_configuration(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastadmin\api\service.py", line 414, in get_configuration
    current_user_id = await get_user_id_from_session_id(session_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastadmin\api\service.py", line 62, in get_user_id_from_session_id
    if not user_id or not await admin_model.get_obj(user_id):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastadmin\models\base.py", line 415, in get_obj
    obj = await self.orm_get_obj(id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\fastadmin\models\orms\sqlalchemy.py", line 314, in orm_get_obj
    return await session.get(self.model_cls, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 462, in get
    result_obj = await greenlet_spawn(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 165, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\orm\session.py", line 3540, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\orm\session.py", line 3672, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\orm\loading.py", line 668, in load_on_pk_identity
    session.execute(
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2229, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\orm\session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\orm\context.py", line 253, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\sql\elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\engine\default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 515, in execute
    self._adapt_connection.await_(
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 494, in _prepare_and_execute
    self._handle_exception(error)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 444, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Владислав\PycharmProjects\mitsu_api\virtualenv\Lib\site-packages\sqlalchemy\dialects\postgresql\asyncpg.py", line 717, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.DataError'>: invalid input for query argument $1: '3' ('str' object cannot be interpreted as an integer)
[SQL: SELECT accounts.id AS accounts_id, accounts.nickname AS accounts_nickname, accounts.authentication_name AS accounts_authentication_name, accounts.password_hash AS accounts_password_hash, accounts.tag AS accounts_tag, accounts.role AS accounts_role, accounts.avatar_url AS accounts_avatar_url 
FROM accounts 
WHERE accounts.id = $1::BIGINT]
[parameters: ('3',)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
```

**Comment by vsdudakov** [comment]
Let me fix it

**Comment by vsdudakov** [comment]
https://github.com/vsdudakov/fastadmin/compare/0.1.36...0.1.37 commit should fix the issue. Release 0.1.37

**Comment by vsdudakov** [comment]
Please reopen in case it is reproducible on 0.1.37 on your side @kuyugama
